version: "3.8"

services:
    backend:
        build: .
        container_name: backend
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        volumes:
            - .:/backend/
        ports:
            - "8000:8000"